### ISSUE TITLE
GWT Compilation Out Of Memory 

### ISSUE THREAD

**Issue by vinyjais** [gwtproject/gwt#9656]
**GWT version:** 2.6.1 
**Browser (with version):** firefox
**Operating System:** Windows

---

##### Description

My Application is producing 1.6GB of war file and taking 7 to 8 hrs. for complete build of 5 permutation.
**configuration of machine on which we are compiling is:**
OS: windows server 2012 R2
RAM: 64GB
Processor: Intel R ZEON R CPU E3-1225 V5 
Core : 4
**we have defined gwt compile parameters as follows:**
GWT Compiler JVM Arguments: -Xmx61440M
GWT Dev Mode JVM Arguments: -Xmx61440M
GWT Test JVM Arguments: -Xmx61440M

we are facing two major problems
1. from last few days we are receiving out of memory error during compilation.
2. it is taking very huge time to build.

we wish our project could break into smaller sections (modules compiled individually separately) and bundled in a single war at the time of release. like we use multiple dlls and use it in single exe. and in case of changes in any dll we need not to build whole exe again instead we only compile a dll and deploy it to client.

any suggestion \ help will be highly appreciated.

thank you!

**Comment by vinyjais** [comment]
[compiler param & compilation error.docx](https://github.com/gwtproject/gwt/files/2961479/compiler.param.compilation.error.docx)

**Comment by niloc132** [comment]
This might be a better question for stackoverflow or the mailing list than as a bug report.

That said, this might need to focus on how much code you have too, and do some standard java memory profiling - the garbage collector can be configured based on your needs. From a GWT perspective if you're concerned about war size and compile times, collapsing all permutations into one will create a small increase in compiled size per browser (though I can't imagine that if the app is this massive, that it can actually run in IE9 or 10 anyway) with a huge reduction in compile time (especially with only one worker, as the attached doc says)

Some more history would help too, what sorts of recent changes occurred to make it need more memory, etc ("was it this big 6 months ago", "how long ago did the build start taking over an hour", etc). Almost certainly this is too big to run SOYC, but huge numbers of split points can be very detrimental to compile times as well - disabling or pruning ones that are too small to be useful can make a large difference.

**Comment by vinyjais** [comment]
It is taking more than one hour from very long period of time. We are working on this application from 3 years and yet it is only 35% completed. There are more than 100 modules in the overall application having only one entry point. We are facing this issue from very prolonged time.

We don't want to disable split points as that may cause to build larger javascript files by gwt compiler which may eventually take larger download interval while loading of application as this is only a single page web application.

**Comment by niloc132** [comment]
I'm not necessarily saying you should disable them entirely, just that you should carefully look at what kind of code they are actually creating - if they are only 10kb or less, they should be grouped up into fewer, bigger split points to avoid making the compiler spend too much time just sorting out that most of them are empty and useless. Remember: when any two or more split points share some content, that means _all_ of that content goes into one giant "leftover" split point, which must then be downloaded before any other split point. I've seen "large" apps (only 250-500k lines of code or so) with hundreds of split points which ended up taking 30% or more of their compile time just to make 80% of this split points into tiny pieces, and require that well over half of the whole app gets downloaded just to start the page - this is the opposite of what the developers usually intend. Yours sounds like it must be on the order of 5x that (guesswork, based on the memory usage, it could be far bigger based on that compile time?), if it is already unmanageable, it is only going to get worse as time goes on.

If you are still not finished with such a huge app, I can't emphasize enough the importance of making sure you have a good modularization strategy from the beginning (akin to the dll vs exe you described before). 

I'm going to close this here, this is not a bug in the GWT compiler per se, but how it is being used in this case, at least from the information you've given so far. Discussing this on the https://groups.google.com/forum/#!forum/google-web-toolkit mailing list (or a private email if you want to talk about specifics you can't post here) seems like the best approach until we have something actionable that we can file as a bug report to address within GWT itself.

**Comment by vinyjais** [comment]
My mail id is **viny.jais@gmail.com** we may discus it further on it. 

is there any relation between split points & *.cache.html files.

**Comment by vinyjais** [comment]
what should be the supposed ideal time of compilation for my application. as I have mentioned the size of war generated after compilation & keeping the system configuration in mind.

**Comment by jnehlmeier** [comment]
How many lines of client/shared code does the application have? I assume the war file contains quite a bit other stuff than just the pure JS code of GWT (source maps, images, whatever). Or do you use ClientBundle + TextResource/DataResource and embed large data into the JavaScript?

1.6GB of pure JS code sounds unlikely.

**Comment by vinyjais** [comment]
1. deferredjs folder contains 441mb of js files
2. *.gwt.rpc files are 308mb cumulative
3. *.cache.html files are 27.9mb cumulative
4. *.nocache.js is 8kb

**Comment by jnehlmeier** [comment]
Given the *.gwt.rpc files are just plain text, listing all classes (with some meta information) that GWT thinks might go over the wire, you either send a large number of different classes back and forth or you don't but use common interfaces in your GWT-RPC method declaration (directly or indirectly), e.g. Serializable, Collection, Set, List. 
If you then have a large class path that GWT compiler can see, then GWT will generate lots of serializer classes for all visible implementations of these interfaces, regardless if you actually use these implementations or not. That can produce pretty large *.gwt.rpc files as well as a lot of JS code that is actually never needed at runtime.

Could this be the case? Have you looked through these *gwt.rpc files and check if they contain lots of classes you actually never use?

**Comment by vinyjais** [comment]
we have more than 300 forms and every forms have its own model class to transit data.   
means we have more than 300 model class which is implemented Serializable , IsSerializable

public class KeyField implements Serializable , IsSerializable{

    private String sharedKeyFieldCode;
    private String sharedKeyFieldName;
    private String sharedPreparedBy;
    private String sharedModifiedBy;

    public KeyField() {

    }

    public KeyField(String KeyFieldCode, String KeyFieldName) {
        this.sharedKeyFieldCode = KeyFieldCode;
        this.sharedKeyFieldName = KeyFieldName;
    }

    public String getSharedPreparedBy() {
        return sharedPreparedBy;
    }

    public void setSharedPreparedBy(String sharedPreparedBy) {
        this.sharedPreparedBy = sharedPreparedBy;
    }

    public String getSharedModifiedBy() {
        return sharedModifiedBy;
    }

    public void setSharedModifiedBy(String sharedModifiedBy) {
        this.sharedModifiedBy = sharedModifiedBy;
    }

    public int getSharedKeyFieldHashCode() {
        return this.hashCode();
    }

    public String getSharedKeyFieldCode() {
        return sharedKeyFieldCode;
    }

    public void setSharedKeyFieldCode(String sharedKeyFieldCode) {
        this.sharedKeyFieldCode = sharedKeyFieldCode;
    }

    public String getSharedKeyFieldName() {
        return sharedKeyFieldName;
    }

    public void setSharedKeyFieldName(String sharedKeyFieldName) {
        this.sharedKeyFieldName = sharedKeyFieldName;
    }

    public void copy(KeyField keyField) {
        keyField.setSharedKeyFieldCode(this.getSharedKeyFieldCode());
        keyField.setSharedKeyFieldName(this.getSharedKeyFieldName());
        keyField.setSharedPreparedBy(this.getSharedPreparedBy());
        keyField.setSharedModifiedBy(this.getSharedModifiedBy());
    }
}


public class Find_Mdl extends KeyField implements Serializable, IsSerializable {

        private String  voucherDate,ambulanceNumber,patientName,inTransitDate,inTransitTime,driverName; 

    public Find_Mdl() {
    }
.
.
.
.
}

**Comment by dnouls** [comment]
We had similar problems in our project.

The main reason for long compile times is indeed the misuse of GWT RPC.

Java devs are trained to use Interfaces while in GWT you should really stick to concrete classes.
So never use Serializable or List or Map in classes that are used with RPC.

For every class that matches gwt will generate serialisers/deserialisers. And it will do so for every rpc service that you define. The worse case is when gwt sees Object as a generic parameter on these interfaces... the compiler actually spits out a warning.

**Comment by vinyjais** [comment]
We are using interfaces for GWT transport models of client and servers as for some production servers like payara, wildfly etc don't allow transportation of model instances if we don't use IsSerializable interface. Moreover our application heavily uses the advantages of oops concepts to reduce the application code.

**Comment by dnouls** [comment]
interfaces are not the problem, but usage of interfaces for collection classes for example in the rpc payloads. For example if you have a model that contains a field of type List<> would already require gwt to generate serialisers for all classes in the classpath the somehow implement List. If you have a field List<Object> then gwt will actually start checking for all classes that implement IsSerializable or Serializable. etc.

Just take a look at the gwt.rpc files, it is a list of all classes for which gwt generated serializers. Many of those types are probably never needed.

**Comment by tbroyer** [comment]
Fwiw, you may want to continue the discussion at https://groups.google.com/d/topic/google-web-toolkit/jaqHKyszh7U/discussion
