### ISSUE TITLE
Restore 1.7  sourceLevel option

### ISSUE THREAD

**Issue by muten84** [gwtproject/gwt#9448]
When i try to migrate from GWT 2.7 to  GWT 2.8 i get the following error during compilation phase:

          [ERROR] Line 69: The method append(boolean) is ambiguous for the type StringBuffer

I just realized this is a Java8 compilation error for the new  Generic Infer Type Target Improve. Infact if i try to compile the same source code with javac 1.7 level compliance it works well. With GWT 2.8 i realized that it's supported only the 1.8 source level and despite the java compiler of the  project runtime compiles successfully all classes, (source an target to 1.7), the GWT compiler tries to recompile all sources with java 1.8 level compliance.  I'm trying to understand if it's possible to use GWT 2.8.0 with java 7, or it's required minimum java 1.8.

However I can't believe Java broke backward compatibility, it's the first time i see that the compiler gives an error for source code written with older java versions. This is very frustrating.

**Comment by jnehlmeier** [comment]
Internally GWT 2.8 uses JDT with sourceLevel 1.8 because GWT provides Java 8 API emulation which requires Java 8 syntax. So all classes compiled with GWT compiler must be compatible to Java 8, regardless of the JVM your project uses. You can still use Java 7 with GWT 2.8, however it can break some GWT libraries (for example google-gin won't work with Java7 + GWT 2.8).

Wondering why you get errors for StringBuffer because it is emulated by GWT and I would assume the error should have popped up during release testing.

**Comment by muten84** [comment]
Thanks for reply and the JDT info. Unfortunately, i use an older version of the Sencha ExtJs/GXT library that has some methods using Generics written in a way that is not supported anymore in Java8.  Suppose to have to following GenericType method:

               public <S> S get() {
			return this.<S>set((S) t);
		}
 and a set of overloaded methods like the append method of StringBuffer class, if i try to call the method in this way:

           StringBuffer buf = new StringBuffer();
           buf.append(this.get()); // <---- compilation error (in Java7 it works well)
           buf.append(this.<String>get()); //it will compile

So this is definitely a Java8 compatiblity issue. However the issue i opened is focused on the possibility to use the 1.7 source level in GWT 2.8.0, the sense of this request is for using GWT 2.8.0 features (like JsInterop) in projects not requiring Java8 syntax.

**Comment by jnehlmeier** [comment]
You would have to patch ExtJs or update its version in case they have fixed it in a more recent version. Alternatively you can try building your own GWT by restoring the 1.7 source level and deleting all Java 8 emulation (Basically rollback all the corresponding commits since GWT 2.7 and hope that it works).

**Comment by muten84** [comment]
Ok thanks for all ... i appreciate your suggestions. In my case I think it's more convenient to patch the affected code.
