### ISSUE TITLE
Unable to access ArrayList elements from JS

### ISSUE THREAD

**Issue by tazle** [gwtproject/gwt#9422]
During the summer we wrote some proof of concept JsInterop code based on GWT master branch. Our code passed an an `ArrayList<ValueType>` to a JS callback that was represented on GWT side as
```
@JsFunction
public interface Callback {
    void handle(List<ValueType> aList);
}
```

We were able to access the list elements on JS side using Java List methods like `.get(0)`, but this no longer works with GWT 2.8.0-rc2: `SEVERE: (TypeError) : elements.get is not a function`

In ticket https://github.com/gwtproject/gwt/issues/9364 there is some talk about "JsInterop base classes", which I presume have gone missing from mainline GWT between June-July 2.8.0-SNAPSHOT and current 2.8.0-rc2. Is there something else I should be including in my project, or some other preferred way to pass collection to JS code?

**Comment by tbroyer** [comment]
This is possibly related to #9369 (https://github.com/hpehl/gwt/commit/ca8ad7bc140bc23b237620c41d755ef787bd97b1). TL;DR: you have to pass `-generateJsInteropExports` (even to SDM) if you want to be able to call `@JsMethod`s (including `java.util.List#get(int)`) from JS.
(that is, if I understood those changes correctly)

**Comment by tazle** [comment]
Hi, I think that would explain the issue. I'll try it on Monday.

Thanks for the prompt response :)

**Comment by tazle** [comment]
Looking at the code more carefully, it seems that the generates JS for ArrayList has ...AtIndex methods for the methods that take an index in Java:
```
stations
  java_util_ArrayList_ArrayList__V {java_util_ArrayList_array: Array[16]}
    java_util_ArrayList_array: Array[16]
    __proto__: Object
      add: java_util_ArrayList_add__Ljava_lang_Object_2Z(o)
      addAll: java_util_ArrayList_addAll__Ljava_util_Collection_2Z(c)
      addAllAtIndex: java_util_ArrayList_addAll__ILjava_util_Collection_2Z(index_0, c)
      addAtIndex: java_util_ArrayList_add__ILjava_lang_Object_2V(index_0, o)
      clear: java_util_ArrayList_clear__V()
      constructor: Objectcontains: java_util_ArrayList_contains__Ljava_lang_Object_2Z(o)
      getAtIndex: java_util_ArrayList_get__ILjava_lang_Object_2(index_0)
      indexOf: java_util_ArrayList_indexOf__Ljava_lang_Object_2I(o)
      isEmpty: java_util_ArrayList_isEmpty__Z()
      iterator__Ljava_util_Iterator_2: java_util_ArrayList_iterator__Ljava_util_Iterator_2()
      java_lang_Object__1_1_1clazz: java_lang_Class_Class__Vjava_lang_Object_castableTypeMap: ObjectlastIndexOf: java_util_ArrayList_lastIndexOf__Ljava_lang_Object_2I(o)
      package_private$java_util$indexOf__Ljava_lang_Object_2II: java_util_ArrayList_indexOf__Ljava_lang_Object_2II(o, index_0)
      package_private$java_util$lastIndexOf__Ljava_lang_Object_2II: java_util_ArrayList_lastIndexOf__Ljava_lang_Object_2II(o, index_0)
      private$java_util_ArrayList$$init__V: java_util_ArrayList_$init__V()
      remove: java_util_ArrayList_remove__Ljava_lang_Object_2Z(o)
      removeAtIndex: java_util_ArrayList_remove__ILjava_lang_Object_2(index_0)
      removeRange__IIV: java_util_ArrayList_removeRange__IIV(fromIndex, endIndex)
      setAtIndex: java_util_ArrayList_set__ILjava_lang_Object_2Ljava_lang_Object_2(index_0, o)
      size: java_util_ArrayList_size__I()
      sort__Ljava_util_Comparator_2V: java_util_ArrayList_sort__Ljava_util_Comparator_2V(c)
      toArray: java_util_ArrayList_toArray___3Ljava_lang_Object_2()
      toArray___3Ljava_lang_Object_2_3Ljava_lang_Object_2: java_util_ArrayList_toArray___3Ljava_lang_Object_2_3Ljava_lang_Object_2(out)
      __proto__: Object
```

Is this something we should expect?


We do have `<generateJsInteropExports>true</generateJsInteropExports>` in the Maven plugin configuration, and the GWT compiler command line looks about as follows:
```
java -classpath <long, omitted here> com.google.gwt.dev.Compiler -logLevel INFO -style DETAILED -war C:\path\to\project\module\target\gwt-output -localWorkers 4 -failOnError -compileReport -XfragmentCount -1 -sourceLevel 1.8 -generateJsInteropExports -optimize 0 -extra C:\path\to\project\module\target\extra -gen C:\path\to\project\module\target\.generated com.ourapp.App
```

**Comment by tbroyer** [comment]
Ah yes, see https://github.com/gwtproject/gwt/commit/ca6364f882b55b7e9b5f5cbbc3220b14677eb2ae

The previous change that introduced the `@JsType` on collections was (a bit more than) 2 weeks earlier: https://github.com/gwtproject/gwt/commit/45e6ff83bc22f6dce648ed4cd21eeb24fe0b3e15
So you must have taken a snapshot between June 22nd and July 9th.

**Comment by tazle** [comment]
Ok, good to know.

Is there some way to discover the changed method names? Or the types that have @JsType annotation? Are the JS method names visible in Javadocs, for example?
