### ISSUE TITLE
String.isEmpty() fails on native JS strings from @JsType(isNative=true) after #10091

### ISSUE THREAD

**Issue by ihorshu** [gwtproject/gwt#10298]
CharSequence.isEmpty() added in 2.13 breaks devirtualization when called on a String field of a @JsType(isNative=true) object. 
At runtime: TypeError: this$static.isEmpty__Z is not a function.

**Comment by niloc132** [comment]
Thanks, do you have a minimal reproducer? A quick test of the devirtualizer seems to show that isEmpty method is remade into a static `String.isEmpty__Z__devirtual$` as expected, though this only handles the devirtualizer's behavior, not all the way to JS.

```
  public void testDevirtualizeStringFieldAccess() throws UnableToCompleteException {
    addSnippetImport("jsinterop.annotations.JsType");
    addSnippetImport("jsinterop.annotations.JsOverlay");
    addSnippetClassDecl(
        "@JsType(isNative=true) public static class NativeClass {",
        "  public String field;",
        "}");
    optimize("void", "boolean b = new NativeClass().field.isEmpty();")
        .intoString("boolean b = String.isEmpty__Z__devirtual$((new EntryPoint$NativeClass()).field);");
  }
```

**Comment by ihorshu** [comment]
Generated with AI.
The key detail: the runtime error is this$static.isEmpty__Z is not a function — note it's calling isEmpty__Z (instance method), not isEmpty__Z__devirtual$. So the devirtualizer isn't
  being applied in this path.

  Minimal reproducer:

   // 1. Native JS type with a String field
```
   @JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
   public class NativeObj {
       public String value;
   }
```
   
   // 2. Call isEmpty() on the native string field
```
   public class EntryPoint implements com.google.gwt.core.client.EntryPoint {
       @Override
       public void onModuleLoad() {
           NativeObj obj = makeObj();
           // This compiles fine but fails at runtime:
           //   TypeError: this$static.isEmpty__Z is not a function
           boolean empty = obj.value.isEmpty();
           GWT.log("empty=" + empty);
       }
   
       private static native NativeObj makeObj() /*-{
           return { value: "hello" };
       }-*/;
   }
```

  What happens: obj.value returns a raw JS string at runtime. The compiler sees the declared type as java.lang.String but apparently skips devirtualization for field accesses on 
  @JsType(isNative=true) objects, emitting a direct instance call to isEmpty__Z which doesn't exist on native JS strings.

  Workaround: obj.value.length() > 0 works — length() is correctly devirtualized.

**Comment by niloc132** [comment]
>  The key detail: the runtime error is this$static.isEmpty__Z is not a function — note it's calling isEmpty__Z (instance method), not isEmpty__Z__devirtual$. So the devirtualizer isn't being applied in this path.
I understand how that appears to be true, but odds are, the static impl is being inlined. I'm not used to the __Z notation on a method in GWT - J2CL follows that convention though.

> What happens: obj.value returns a raw JS string at runtime. The compiler sees the declared type as java.lang.String but apparently skips devirtualization for field accesses on

Odds are it isn't skipping it, but inlining it away, but I'm not clear why you're getting an instance method out of the deal, instead of a length access. Here's the test I wrote for the compiler, based on your sample, and the debugging I'm using to see what happens:
```java
  @JsType(isNative=true)
  public static class NativeObjWithStringField {
    public String value;
  }
  private native NativeObjWithStringField makeObj() /*-{
    return {value: 'asdf'};
  }-*/;

  public void testNativeStringFieldIsEmpty() {
    NativeObjWithStringField obj = makeObj();
    assertFalse(obj.value.isEmpty());
  }
```

This passes, and generates this code in draft:
```
_.testNativeStringFieldIsEmpty = function testNativeStringFieldIsEmpty(){
  var obj;
  obj = this.makeObj();
  jf.assertFalse_0(jl.isEmpty__Z__devirtual$(obj.value));
};
```
And in optimized output, we see that it was correctly inlined away:
```
_.testNativeStringFieldIsEmpty = function testNativeStringFieldIsEmpty(){
  var obj;
  obj = {value:'asdf'};
  assertFalse_0(obj.value.length == 0);
};
```

At no time in the intermediate AST do I see a isEmpty__Z, but it is possible that it appeared then disappeared within a single pass, instantly inlined away - I didn't dig more deeply yet.

JsInterop property accessors should not be treated specially by the compiler anyway, at least not for devirtualization. I'm afraid I don't know yet what could be going on for you - can you try a standalone app to reproduce this, so you can share the full setup? Something seems fishy.

**Comment by niloc132** [comment]
If I examine the draft build more closely and also test a plain StringBuilder (so that we have two CharSequence instances I can easily examine), it starts to look _closer_ to what you describe, but the calling conventions look wrong still.

I added one line to the test method above:
```java
    assertFalse(new StringBuilder("asdf").isEmpty());
```

```javascript
jl.isEmpty__Z__devirtual$ = function isEmpty__Z__devirtual$(this$static){
  jl.$clinit_String();
  return instanceOfString(this$static)?jl.$isEmpty_0(this$static):this$static.isEmpty_1();
};
jl.isEmpty__Z__devirtual$_0 = function isEmpty__Z__devirtual$_0(this$static){
  return jl.$isEmpty_0(this$static);
};
```
The first is the actual String.isEmpty devirtualized call, the second is never used, and I haven't yet worked out where it came from. The first has the ability to be inlined and might statically decide that it isn't being called on a String at all, so will attempt to use dynamic dispatch to call `isEmpty_1()` on "this" - close to what you're seeing, but only one underscore, and no Z, just the usual "use the next int" convention.

The only isEmpty_1 is defined in this way:
```javascript
_.isEmpty_1 = function isEmpty_0(){
  return jl.$isEmpty(this);
};
```
As an instance method it is just a call to another static method:
```javascript
jl.$isEmpty = function $isEmpty(this$static){
  return jl.length__I__devirtual$(this$static) == 0;
};
```
Which itself is just the length() method, devirtualized.

Going back to $isEmpty_0:
```javascript
jl.$isEmpty_0 = function $isEmpty_0(this$static){
  return jl.$isEmpty(this$static);
};
```
This is the same thing. I'm not quite clear why the compiler deemed this a good idea, but I also can say that the optimized impl doesn't show any of this, so I'm not actually too worried.

For completeness, the draft impl of the test itself:
```javascript
_.testNativeStringFieldIsEmpty = function testNativeStringFieldIsEmpty(){
  var obj;
  obj = this.makeObj();
  jf.assertFalse_0(jl.isEmpty__Z__devirtual$(obj.value));
  jf.assertFalse_0(jl.isEmpty__Z__devirtual$(new jl.StringBuilder_0('asdf')));
};
```

and finally the optimized impl:
```javascript
_.testNativeStringFieldIsEmpty = function testNativeStringFieldIsEmpty(){
  var obj;
  obj = {value:'asdf'};
  assertFalse_0(obj.value.length == 0);
  assertFalse_0((new StringBuilder_0('asdf')).string.length == 0);
};
```

https://github.com/tbroyer/gwt-maven-archetypes would be a good starting point for a simple project that you could share, which hopefully would make the bug clearer, because I'm definitely missing something.

**Comment by ihorshu** [comment]
Here's the actual browser error, compiled JS evidence, and our build config.

  Build config:

   - GWT
    2.13.0
   - gwt-material-addins
    2.8.5 (com.github.gwtmaterialdesign)
   - draftCompile=true, style=DETAILED

  Browser error:

   Uncaught TypeError: this$static.isEmpty__Z is not a function
       at java_lang_String_isEmpty_1_1Z_1_1devirtual$__Ljava_lang_CharSequence_2Z (<main>.js:2374:182)
       at ...MaterialFileUploader_convertUploadFile... (<deferred>.js:50142:120)

  Line 2374 — the exact failing line in the compiled JS:

   JsStackEmulator_returnTemp = com_google_gwt_lang_Cast_instanceOfString__Ljava_lang_Object_2Z(this$static)
       ? java_lang_String_$isEmpty__Ljava_lang_String_2Z(this$static)
       : this$static.isEmpty__Z();  // ← crashes here

  instanceOfString:

   function com_google_gwt_lang_Cast_instanceOfString__Ljava_lang_Object_2Z(src_0){
     return typeof src_0 === 'string';
   }

  convertUploadFile calling site (deferred fragment):

   if (com_google_gwt_lang_Cast_jsNotEquals__Ljava_lang_Object_2Ljava_lang_Object_2Z(file.lastModifiedDate, null)
       && !java_lang_String_isEmpty_1_1Z_1_1devirtual$__Ljava_lang_CharSequence_2Z(file.lastModifiedDate)) {

  Root cause: The gwt-material-addins Blob.java declares lastModifiedDate as public String in a @JsType(isNative=true) class, but the browser's File.lastModifiedDate returns a JS
  Date object, not a string. At runtime:

   1. typeof new Date() === 'string' → false
   2. Falls to this$static.isEmpty__Z() → Date has no such method → TypeError

  This presumably worked before GWT 2.13 because String.isEmpty() was a String-only method — the compiler could statically resolve it without the instanceOfString runtime check. With
  CharSequence.isEmpty() added in 2.13, the devirtualizer now generates the runtime type dispatch, which exposes the type mismatch.

  So this may actually be a gwt-material-addins bug (wrong type declaration) that 2.13's CharSequence.isEmpty() change happened to surface. Would you agree, or is there a case that
  the devirtualizer should handle @JsType(isNative=true) fields more defensively?

**Comment by niloc132** [comment]
That's an interesting turn of events, but I'm afraid the bug is squarely on GMD for this - Blob's lastModifiedDate must not be a String. In the past this worked because a JS `Date` has no `length` property at all, so the length check ends up testing `undefined > 0`, which is nonsense in any language, and false in JS. 

If you set optimizationLevel to 1, that probably is enough to inline away the length check, and costs only slightly more than draft compile. Note that your use of split points _probably_ costs a lot more than any amount of optimizations though - if you want your build to be faster, consider turning split points off entirely.

It could be nice to defensively write GWT to test everything declared as a String, but that would also be quite expensive at runtime, and add a fair bit of compiled size.

I'm sorry for not testing DETAILED output - I'm not accustomed to seeing it, so I missed that was how your `isEmpty__Z` was named. 


---


Looking at GMD specifically now, I'm not really sure what they intend to happen here - is lastModifiedDate part of Blob anyway, or something specific GMD-addins is doing? It isn't part of the Blob type that browsers support as far as I can tell - MDN doesn't list it (though [`File` has a lastModified](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified) _number_ property), and when I construct my own Blob in the browser, it doesn't have one (only tested Chrome/FF). GMDA's [DefaultBlobProvider](https://github.com/GwtMaterialDesign/gwt-material-addins/blob/master/src/main/java/gwt/material/design/addins/client/fileuploader/base/DefaultBlobProvider.java#L34) is explicitly assigning a string (from a Java date, not the same as a Js Date), which seems at least self-consistent, but disagrees with what your comment says is happening. Is it possible that you have your own custom FileProvider that is assigning a date in raw JS that disagrees?

GMD-addins's File extends from Blob, which correctly maps to the browser's own types, and when I instantiate File directly in the browser as I said above it has a `lastModified`, not `lastModifiedDate`, and it is a number, not a Date.

There are other inconsistencies as well - GMD says that Blob.size is a String, while it seems it must be a number if reading from the browser. `type`, `xhr`, and `previewElement` seem made-up as well - though at least File has `type`.

It is fortunate that this worked for so long, but I think GMD is clearly making up their own idea of what the browser should have, and GWT can't bridge that gap. I am sorry that you're encountering a bug as a result - can you try bumping up optimizationLevel as I suggested to see if that happens to inline enough to at least make the code work? Forking and fixing GMDA might be the best option to proceed though, given these other questions.

**Comment by ihorshu** [comment]
Thanks for investigating this so thoroughly! Based on your analysis, this is indeed a gwt-material-addins issue — the Blob.lastModifiedDate field is declared as String in 
  @JsType(isNative=true) while the browser returns a JS Date object. The instanceOfString check in the devirtualized isEmpty() correctly fails because it's not a string.

  A workaround has been applied on our side. I'll report the type mismatch to the GMD repo.

**Comment by niloc132** [comment]
Sorry, I cannot see anything that says the browser assigns a Date to `Blob.lastModifiedData` - no browser I tested did this, nor does any spec say this that I can find. `File.lastModified` is a _number_, not a date, and has a different name anyway.

**Comment by jnehlmeier** [comment]
@ihorshu `File.lastModifiedDate` is deprecated and may or may not exist: https://developer.mozilla.org/en-US/docs/Web/API/File/lastModifiedDate

The library should definitely use `File.lastModified` instead.

Both properties are part of `File` and not `Blob` so the library should move it from their `Blob` JsType up to their `File` JsType.
