### ISSUE TITLE
Compilation error after upgrading to 2.8

### ISSUE THREAD

**Issue by tskardal** [gwtproject/gwt#9461]
After upgrading to 2.8.0 I get this compilation error. @niloc132 suggests that this could be related to [this jdt bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469653)
```
[INFO] Compiling module some.Module
[INFO]    Ignored 147 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]    [ERROR] Errors in 'file:/Users/thomas.skardal/Work/.../AbstractGenericEditorWizardPage.java'
[INFO]       [ERROR] Line 69: Type mismatch: cannot convert from List<capture#2-of ? extends ViolationRenderer<Object>> to List<? extends ViolationRenderer<E>>
[INFO]    Tracing compile failure path for type '...AbstractGenericEditorWizardPage'
[INFO]       [ERROR] Errors in 'file:/Users/thomas.skardal/Work/.../AbstractGenericEditorWizardPage.java'
[INFO] [ERROR] Line 69: Type mismatch: cannot convert from List<capture#2-of ? extends ViolationRenderer<Object>> to List<? extends ViolationRenderer<E>>
```

The involved code:

```java
public interface ViolationRenderer<E> extends ConstraintViolationSelector<E> {
    String render(ConstraintViolation<E> violation);
}
```

```java
public abstract class AbstractGenericEditorWizardPage<E extends Entity, T> extends AbstractWizardPage
        implements HasSelector<E>, HarInputs, Editor<T> {    
        
    // ...
    
    @Override
    public final List<? extends ViolationRenderer<E>> getPageViolationRenderers() {
        return driverSelector.getRenderers();
    }
    
    // ...
}
```
```java
public class DriverViolationSelector {
  
    // snip
    
    public <E> List<? extends ViolationRenderer<E>> getRenderers() {
        final List<ViolationRenderer<E>> renderers = Lists.newLinkedList();
        driver.accept(new EditorVisitor() {
            @Override
            public <T> void endVisit(EditorContext<T> ctx) {
                String path = ctx.getAbsolutePath();
                if (path.equals(EditorContext.ROOT_PATH)) {
                    renderers.add(new ViolationMessageRenderer<E>(new PathConstraintViolationSelector<E>(path)));
                } else {
                    renderers.add(new ListAwareViolationRenderer<E>(new RegexPathConstraintViolationSelector<E>(path + ".*")));
                }
            }
        });
        return renderers;
    }
    
    // snip
}
```

**Comment by tskardal** [comment]
A workaround is to change 

```
return driverSelector.getRenderers();
```
to
```
return driverSelector.<E>getRenderers();
```

**Comment by rluble** [comment]
Type checking is indeed performed by JDT. Java 8 has slightly different type inference and type checking semantics where code that type checks in Java 7 might not in Java 8 and viceversa. On top of that JDT has a few open bugs related to Java 8 type checking/inference. 

Let's label JDT bugs explictely and see if they persist when JDT gets updated.

**Comment by niloc132** [comment]
If I'm reading the linked JDT bug correctly, they identified that JDT was correct and javac was wrong, and Java was fixed in https://bugs.openjdk.org/browse/JDK-8039214 for Java 9, so this issue can be closed - the error was correct.
